### ISSUE TITLE
bb10 example doesn't work with latest Web Works 2.0 release 2.1.0.13

### ISSUE THREAD

**Issue by RahimKanjiyani** [blackberry/bbUI.js#1021]
Looks like the bb10 example is built against cordova.v2.0.0.71. The latest version of webworks is using cordova 2.1.0.13. Please update the example. I am getting following error messages upon compilation.

Error: Cannot find module 'exit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
